client:
  host: "localhost:3000"
  railscontact: "https://www.railstutorial.org/contact"
  railshelp: "https://www.railstutorial.org/help"
  railsbook: "https://www.railstutorial.org/book"
  railshome: "https://www.railstutorial.org/"
  railsscreencast: "http://screencasts.railstutorial.org/"
  railsnews: "http://news.railstutorial.org/"
  mh: "http://www.michaelhartl.com/"
enabled_locales: ["en", "vi"]
max_name: 50
max_email: 255
min_password: 6
username: sample_app
remember_checked: "1"
remember_unchecked: "0"
